### ISSUE TITLE
Mac以外でのブラウザオープン

### ISSUE THREAD

**Issue by fnobi** [fnobi/koko#14]

**Comment by yumetodo** [comment]
https://github.com/fnobi/koko/blob/2e3756f786e54c29feacfddbe046c8292bcf7374/index.js#L144

```js
child_process = require('child_process'),
.
.
.
child_process.exec('open ' + openURL, callback);
```

のようになっているが、

https://github.com/sindresorhus/opn

というものがあるので

```js
const opn = require('opn');
.
.
.
opn(openURL);
```

のように書けるように思える。

**Comment by nobii** [comment]
@yumetodo 情報ありがとうございます！便利ですね。
[0.6.0](https://github.com/fnobi/koko/releases/tag/0.6.0) にて取り込みました。

**Comment by yumetodo** [comment]
Windows10での動作を確認しました。
対応ありがとうございました。

**Comment by nobii** [comment]
ありがとうございました！
